version: '3.9'
services:
  cloudflareddns:
    image: timothyjmiller/cloudflare-ddns:latest@sha256:73edef388bab61c5a1df8171d5f3a0bd6b398e24e4baec752d63e1cd4044ecea
    hostname: cloudflareddns
    container_name: cloudflareddns__cloudflareddns
    restart: unless-stopped

    environment:
      PUID: 1
      PGID: 1

    volumes:
      - type: bind
        source: ./config.json
        target: /config.json

    networks:
      - default

    deploy:
      resources:
        limits:
          memory: 128m

networks:
  default:
    name: cloudflareddns__default
