version: '3.9'
services:
  cloudflareddns:
    image: timothyjmiller/cloudflare-ddns:latest@sha256:2187e122660d6a2d451ef7c53fd4805c133133f4f47552256352c1e2a7f49ee2
    hostname: cloudflareddns
    container_name: cloudflareddns__cloudflareddns
    restart: unless-stopped

    environment:
      PUID: 1
      PGID: 1

    volumes:
      - type: bind
        source: ./config.json
        target: /config.json

    networks:
      - default

    deploy:
      resources:
        limits:
          memory: 128m

networks:
  default:
    name: cloudflareddns__default
