version: '3.9'
services:
  cloudflareddns:
    image: timothyjmiller/cloudflare-ddns:latest@sha256:37c99677e997710c1bbe9d74c93f2e3b8de3457a5ca6e28643e251b38ed05311
    hostname: cloudflareddns
    container_name: cloudflareddns__cloudflareddns
    restart: unless-stopped

    environment:
      PUID: 1
      PGID: 1

    volumes:
      - type: bind
        source: ./config.json
        target: /config.json

    networks:
      - default

    deploy:
      resources:
        limits:
          memory: 128m

networks:
  default:
    name: cloudflareddns__default
