version: '3.9'
services:
  cloudflareddns:
    image: timothyjmiller/cloudflare-ddns:latest@sha256:dd3696223fbc502178ba37277d98d010cdb4c4f0d93e31ab79cd9c9060d06c52
    hostname: cloudflareddns
    container_name: cloudflareddns__cloudflareddns
    restart: unless-stopped

    environment:
      PUID: 1
      PGID: 1

    volumes:
      - type: bind
        source: ./config.json
        target: /config.json

    networks:
      - default

    deploy:
      resources:
        limits:
          memory: 128m

networks:
  default:
    name: cloudflareddns__default
