version: '3.9'
services:
  cloudflareddns:
    image: timothyjmiller/cloudflare-ddns:latest@sha256:c4392e3a6468cad38af3f2bd89648d082cfda56ff8afee7bc2b7247027f3cb0c
    hostname: cloudflareddns
    container_name: cloudflareddns__cloudflareddns
    restart: unless-stopped

    environment:
      PUID: 1
      PGID: 1

    volumes:
      - type: bind
        source: ./config.json
        target: /config.json

    networks:
      - default

    deploy:
      resources:
        limits:
          memory: 128m

networks:
  default:
    name: cloudflareddns__default
