name: lint actions

on:
  pull_request:
    paths:
      - '.github/workflows/**'

jobs:
  lint-actionlint:
    runs-on: ubuntu-22.04

    steps:
       - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

       - uses: reviewdog/action-actionlint@v1.44.0
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           reporter: github-pr-check
