name: validate compose

on:
  pull_request:
    paths:
      - 'docker-compose.yml'
      - '.github/workflows/validate-compose.yml'

jobs:
  validate-compose:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - uses: actions/setup-node@v4.0.2

      - name: validate
        shell: bash
        run: |
          shopt -s globstar
          set -eux

          for f in **/docker-compose.yml; do
              if ! docker compose --file "$f" config --quiet; then
                  exit 1
              fi
          done

          exit 0
